version: "3.8"

services:
  mgl_db:
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "55661:5432"
    container_name: docker_mgl_db
    hostname: mgl_db
    volumes:
      - postgres-data-mgl:/var/lib/postgresql/data
    networks:
      - mgl_network

volumes:
  postgres-data-mgl:

networks:
  mgl_network:
    driver: bridge